\documentclass{hitec}
\title{Momentum Trading}
\author{Rob Hayward}
\begin{document}
\maketitle

This comes from \href{http://quant.stackexchange.com/questions/19518/thesis-using-momentum-strategies-in-r-tips-on-good-books-guidelines-etc-on-how}{stack exchange}.  

There is some practice in the momentum.R file. 

The \href{https://r-forge.r-project.org/R/?group_id=316}{link to the R-forge page}

This comes from \href{https://quantstrattrader.wordpress.com/2015/09/03/introduction-to-hypothesis-driven-development-overview-of-a-simple-strategy-and-indicator-hypotheses/}{qantstrattrader}. 

Details are in QuantMoment.R

\end{document}